version: '3.8'

services:
  wechatpadpro:
    build: .
    image: wechatpadpro:latest
    container_name: wechatpadpro
    hostname: wechatpadpro
    ports:
      - "8059:8059"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: 12345678
      MYSQL_CONNECT_STR: root:12345678@tcp(mysql:3306)/ipad855?charset=utf8mb4&parseTime=true&loc=Local
      PORT: "8059"
      ADMIN_KEY: "stay33"
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: redis-server --requirepass 12345678
    networks:
      - app-network
    volumes:
      - /root/redis/data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "12345678", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ipad855
    networks:
      - app-network
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]  # 修复密码引用方式
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s  # MySQL 启动较慢，延长检测等待时间

networks:
  app-network:
    driver: bridge
